export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';

export const REQUEST_CITY_KEY_PENDING = 'REQUEST_CITY_KEY_PENDING';
export const REQUEST_CITY_KEY_SUCCESS = 'REQUEST_CITY_KEY_SUCCESS';
export const REQUEST_CITY_KEY_ERROR = 'REQUEST_CITY_KEY_ERROR';

export const REQUEST_WEATHER_PENDING = 'REQUEST_WEATHER_PENDING';
export const REQUEST_WEATHER_SUCCESS = 'REQUEST_WEATHER_SUCCESS';
export const REQUEST_WEATHER_ERROR = 'REQUEST_WEATHER_ERROR';

export const REQ_CURRENT_W_PENDING = 'REQ_CURRENT_W_PENDING';
export const REQ_CURRENT_W_SUCCESS = 'REQ_CURRENT_W_SUCCESS';
export const REQ_CURRENT_W_ERROR = 'REQ_CURRENT_W_ERROR';
